# Generated by Django 2.2.2 on 2019-06-07 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='update_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
