# Generated by Django 2.2.2 on 2019-06-07 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memo_app', '0002_memo_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='update_time',
        ),
        migrations.AddField(
            model_name='memo',
            name='update_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
