# Generated by Django 2.2.4 on 2019-08-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo_app', '0003_auto_20190608_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='update_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
